site:
  url: https://artagym.ru/
  people-class: online-people_rz

google-client:
  url: https://script.google.com/macros/s/AKfycbyqj-geFPaoCccpE3VZTFzouim9qVoSHYPm--lIQF_LM9J08IRf3KBQiz8uKtlk20zy/exec
