site:
  arta-gym:
    name: ${ARTA_NAME}
    url: ${ARTA_URL}
  alex-fitness:
    name: ${ALEX_NAME}
    url: ${ALEX_URL}
  people-class: online-people_rz

google-client:
  url: ${GOOGLE_SHEET_URL}

selenium:
  chrome-url: ${SELENIUM_URL}

server:
  port: 8100
